## DLT

In [21]:
import numpy as np

In [66]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

def dlt(originals, correspondence):  ## numpy arrays of the same size
    traslation = 0
    scale = 0
    
    points_number = np.shape(originals)[0];
    ## o =  orignals
    ## c = correspondence
    o_centroid = np.mean(originals, axis=0)
    c_centroid = np.mean(originals, axis=0)
    
    o_centered = originals - np.tile(o_centroid, (points_number,1))
    c_centered = correspondence - np.tile(c_centroid, (points_number,1))
    
    o_norms = np.linalg.norm(o_centered, axis=1)
    c_norms = np.linalg.norm(c_centered, axis=1)                                              
    
    o_distance = np.sum(o_norms)/points_number
    c_distance = np.sum(c_norms)/points_number
                                          
    o_scale = np.sqrt(2)/o_distance
    c_scale = np.sqrt(2)/c_distance
                                          
    o_homologous = o_scale * o_centered
    c_homologous = c_scale * c_centered
                                          
    A = np.zeros((points_number*2,9))

    zerot = np.array([0,0,0])

    print(o_homologous)
    print(c_homologous)
    for i in range(0, points_number):
        xt = o_homologous[i, :]
        
        wixt = c_homologous[i,2] * xt;
        yixt = c_homologous[i,1] * xt;
        xixt = c_homologous[i,0] * xt;

        A[2*i,:] = np.concatenate((zerot, -wixt, yixt))
        A[2*i + 1,:] = np.concatenate((wixt, zerot, -xixt))
            
    (u,d,v) = np.linalg.svd(A)
    H = np.reshape(v[-1, :], (3,3))
    return H

In [73]:
matrix = [[1, 2, 1],[3,1, 2],[8, 4, 2],[5,3,1],[7,1,1]]

H = dlt(matrix, matrix)

H @ np.array([1, 2, 1])

[[-2.029 -0.107 -0.214]
 [-0.961 -0.641  0.320]
 [ 1.708  0.961  0.320]
 [ 0.107  0.427 -0.214]
 [ 1.174 -0.641 -0.214]]
[[-2.029 -0.107 -0.214]
 [-0.961 -0.641  0.320]
 [ 1.708  0.961  0.320]
 [ 0.107  0.427 -0.214]
 [ 1.174 -0.641 -0.214]]


array([ 0.577,  1.155,  0.577])